### ISSUE TITLE
Build error: multisig.satisfied requires 4 parameters

### ISSUE THREAD

**Issue by golddydev** [SundaeSwap-finance/sundae-yield-v2#6]
Hello, I try to build this project on my side.
But I got error, while building this project.

In validator function **can_unlock** 

> freezer.ak line: 27

```
multisig.satisfied(
      datum.owner,
      ctx.transaction.extra_signatories,
      ctx.transaction.validity_range,
)
```

It uses 3 parameters while the function in your package requires 4.

> lib/sundae/multisig.ak line: 19

```
pub fn satisfied(
  script: MultisigScript,
  signatories: List<ByteArray>,
  valid_range: ValidityRange,
  withdrawals: Dict<StakeCredential, Int>,    ////////////////   <<<----------------
) -> Bool {
  ....
}
```

Can you help me with this issue?
Thank you.

**Comment by Quantumplation** [comment]
Hey! Thanks for raising. We've since updated the multisig library, so you need to either pin the multisig library to a specific version, (which should have been done already, interesting that it's not), or update the script to pass in transaction withdrawals.

Are you trying to exactly reproduce the script we have deployed for sundae yield farming, or just re-purpose it for your own use? That will let me know which one is the best path for you.

**Comment by golddydev** [comment]
Hi, @Quantumplation 
I am going to test this script on my local environment.
I'd love to inspect how Sundae yield farming work.

**Comment by Quantumplation** [comment]
If you want to use the version that sundae yield farming uses, then in `contracts/aiken.toml`, replace the `version = "main"` on line 18 with `version = "2a4e3d8defa023a60be9ff6963d470a81fdb1316"`.

If you're just playing around and want to upgrade, then pass `ctx.transaction.withdrawals` after `ctx.transaction.validity_range` on line 30 of `contracts/freezer/validators/freezer.ak`

We'll likely go with the former, and pin the version of the dependency.

**Comment by golddydev** [comment]
By the way, I found this problem with many aiken projects.
Your project is using Aiken **1.2.0**.
When I build I got error with aiken library's list.ak

>  pub fn and(self: List<Bool>) -> Bool {
> Try removing it.

How you overcome this problem?

**Comment by Quantumplation** [comment]
Yes, you'll also need to pin the version of Aiken to an earlier version, or replace `list.and` with `list.all`, they changed the name of the function in the standard library.
